# さまざまなデータの読み込み

In [2]:
# CSVファイルを読み込む

import os
import pandas as pd

base_url = 'https://raw.githubusercontent.com/practical-jupyter/sample-data/master/anime/'
anime_csv = os.path.join(base_url, 'anime.csv')

df = pd.read_csv(anime_csv)
df.head

<bound method NDFrame.head of        anime_id                                               name  \
0         32281                                     Kimi no Na wa.
1          5114                   Fullmetal Alchemist: Brotherhood
2         28977                                           Gintama°
3          9253                                        Steins;Gate
4          9969                                      Gintama&#039;
5         32935  Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...
6         11061                             Hunter x Hunter (2011)
7           820                               Ginga Eiyuu Densetsu
8         15335  Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...
9         15417                           Gintama&#039;: Enchousen
10         4181                               Clannad: After Story
11        28851                                     Koe no Katachi
12          918                                            Gintama
13         2904                 Code Geass: Hangyaku no Lelouch R2
14        28891                            Haikyuu!! Second Season
15          199                      Sen to Chihiro no Kamikakushi
16        23273                            Shigatsu wa Kimi no Uso
17        24701                      Mushishi Zoku Shou 2nd Season
18        12355                       Ookami Kodomo no Ame to Yuki
19         1575                    Code Geass: Hangyaku no Lelouch
20          263                                     Hajime no Ippo
21           44  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...
22            1                                       Cowboy Bebop
23        30276                                      One Punch Man
24          164                                      Mononoke Hime
25         7311                      Suzumiya Haruhi no Shoushitsu
26        17074                   Monogatari Series: Second Season
27        21939                                 Mushishi Zoku Shou
28          457                                           Mushishi
29         2001                         Tengen Toppa Gurren Lagann
...         ...                                                ...
10456     33036  Suki ni Naru Sono Shunkan wo.: Kokuhaku Jikkou...
10457     33013                                   Super Lovers OVA
10458     27783                                     Sword Gai (TV)
10459     34086                     Tales of Zestiria the X (2017)
10460     34310  Tamagotchi Movie: Tanpen Himitsu no Otodoke Da...
10461     33308  Tantei Opera Milky Holmes: Fun Fun Party Night...
10462     34177                                      Tenshi no 3P!
10463     34449                                     THE REFLECTION
10464     32596                               The Snack World (TV)
10465     34416                The Snack World: Hitogirai no Renny
10466     33473                              Tokyo Futago Athletic
10467     21305                                     Trick or Alice
10468     23275                                         Tsubu★Doll
10469     34474                             Tsukipro The Animation
10470     34498  Uchiage Hanabi, Shita kara Miru ka? Yoko kara ...
10471     34076                                  Uchouten Kazoku 2
10472     33064       Uchuu Senkan Yamato 2202: Ai no Senshi-tachi
10473     33478                                         UQ Holder!
10474     32924                                    Urara Meirochou
10475     32012                                  Utakata Overdrive
10476     34522                          Wake Up, Girls! Shin Shou
10477     34022                                     Whistle! (ONA)
10478     34467                             Yami Shibai 4th Season
10479     32615                                        Youjo Senki
10480     32222  Youkai Watch Movie 3: Soratobu Kujira to Doubl...
10481     34471                               Youkai Watch Movie 4
10482     34284  Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou
10483     34445       Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou
10484     33035                                  Yuyushiki Special
10485     33390                                      Zunda Horizon

                                                   genre     type episodes  \
0                   Drama, Romance, School, Supernatural    Movie        1
1      Action, Adventure, Drama, Fantasy, Magic, Mili...       TV       64
2      Action, Comedy, Historical, Parody, Samurai, S...       TV       51
3                                       Sci-Fi, Thriller       TV       24
4      Action, Comedy, Historical, Parody, Samurai, S...       TV       51
5                 Comedy, Drama, School, Shounen, Sports       TV       10
6                Action, Adventure, Shounen, Super Power       TV      148
7                         Drama, Military, Sci-Fi, Space      OVA      110
8      Action, Comedy, Historical, Parody, Samurai, S...    Movie        1
9      Action, Comedy, Historical, Parody, Samurai, S...       TV       13
10     Drama, Fantasy, Romance, Slice of Life, Supern...       TV       24
11                                Drama, School, Shounen    Movie        1
12     Action, Comedy, Historical, Parody, Samurai, S...       TV      201
13     Action, Drama, Mecha, Military, Sci-Fi, Super ...       TV       25
14                Comedy, Drama, School, Shounen, Sports       TV       25
15                        Adventure, Drama, Supernatural    Movie        1
16                Drama, Music, Romance, School, Shounen       TV       22
17     Adventure, Fantasy, Historical, Mystery, Seine...       TV       10
18                                Fantasy, Slice of Life    Movie        1
19     Action, Mecha, Military, School, Sci-Fi, Super...       TV       25
20                        Comedy, Drama, Shounen, Sports       TV       75
21     Action, Drama, Historical, Martial Arts, Roman...      OVA        4
22       Action, Adventure, Comedy, Drama, Sci-Fi, Space       TV       26
23     Action, Comedy, Parody, Sci-Fi, Seinen, Super ...       TV       12
24                            Action, Adventure, Fantasy    Movie        1
25     Comedy, Mystery, Romance, School, Sci-Fi, Supe...    Movie        1
26       Comedy, Mystery, Romance, Supernatural, Vampire       TV       26
27     Adventure, Fantasy, Historical, Mystery, Seine...       TV       10
28     Adventure, Fantasy, Historical, Mystery, Seine...       TV       26
29              Action, Adventure, Comedy, Mecha, Sci-Fi       TV       27
...                                                  ...      ...      ...
10456                     Comedy, Drama, Romance, School    Movie        1
10457                 Comedy, Drama, Romance, Shounen Ai      OVA        1
10458                                             Seinen       TV  Unknown
10459                         Action, Adventure, Fantasy       TV       12
10460                                                NaN    Movie        1
10461                       Comedy, Mystery, Super Power  Special        1
10462                       Music, School, Slice of Life       TV  Unknown
10463                                Action, Super Power       TV  Unknown
10464                   Adventure, Comedy, Fantasy, Kids       TV  Unknown
10465                   Adventure, Comedy, Fantasy, Kids    Movie        1
10466                                     Comedy, Sports      ONA        8
10467                                            Fantasy      OVA  Unknown
10468                                              Music      OVA        5
10469                                                NaN       TV  Unknown
10470                                              Drama    Movie        1
10471              Comedy, Drama, Fantasy, Slice of Life       TV  Unknown
10472             Action, Drama, Military, Sci-Fi, Space      OVA  Unknown
10473            Action, Fantasy, Magic, Sci-Fi, Shounen      NaN  Unknown
10474                      Comedy, Seinen, Slice of Life       TV  Unknown
10475                                     Fantasy, Music      OVA        1
10476                                       Drama, Music       TV  Unknown
10477                            School, Shounen, Sports      ONA  Unknown
10478                     Dementia, Horror, Supernatural       TV  Unknown
10479                                    Magic, Military       TV  Unknown
10480                         Comedy, Kids, Supernatural    Movie        1
10481                         Comedy, Kids, Supernatural    Movie        1
10482               Drama, Fantasy, Magic, Slice of Life       TV        6
10483               Drama, Fantasy, Magic, Slice of Life       TV        6
10484                                                NaN  Special        1
10485                                                NaN    Movie        1

       rating  members
0        9.37   200630
1        9.26   793665
2        9.25   114262
3        9.17   673572
4        9.16   151266
5        9.15    93351
6        9.13   425855
7        9.11    80679
8        9.10    72534
9        9.11    81109
10       9.06   456749
11       9.05   102733
12       9.04   336376
13       8.98   572888
14       8.93   179342
15       8.93   466254
16       8.92   416397
17       8.88    75894
18       8.84   226193
19       8.83   715151
20       8.83   157670
21       8.83   129307
22       8.82   486824
23       8.82   552458
24       8.81   339556
25       8.81   240297
26       8.80   205959
27       8.80   101351
28       8.78   300030
29       8.78   562962
...       ...      ...
10456     NaN    10668
10457     NaN     5210
10458     NaN     6474
10459     NaN    10848
10460     NaN       51
10461     NaN      610
10462     NaN      359
10463     NaN      242
10464     NaN      107
10465     NaN       36
10466     NaN       75
10467     NaN     4481
10468     NaN     1060
10469     NaN      843
10470     NaN      531
10471     NaN     5934
10472     NaN     2058
10473     NaN     2341
10474     NaN     4305
10475     NaN      649
10476     NaN      381
10477     NaN      381
10478     NaN     1838
10479     NaN     6652
10480     NaN      237
10481     NaN      169
10482     NaN     2593
10483     NaN     4439
10484     NaN     2294
10485     NaN      160

[10486 rows x 7 columns]>

In [3]:
# 指定した列をDataFrameのインデックスにする

# インデックスにする列を番号で指定する
df = pd.read_csv(anime_csv, index_col=0)
df.head

<bound method NDFrame.head of                                                        name  \
anime_id
32281                                        Kimi no Na wa.
5114                       Fullmetal Alchemist: Brotherhood
28977                                              Gintama°
9253                                            Steins;Gate
9969                                          Gintama&#039;
32935     Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...
11061                                Hunter x Hunter (2011)
820                                    Ginga Eiyuu Densetsu
15335     Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...
15417                              Gintama&#039;: Enchousen
4181                                   Clannad: After Story
28851                                        Koe no Katachi
918                                                 Gintama
2904                     Code Geass: Hangyaku no Lelouch R2
28891                               Haikyuu!! Second Season
199                           Sen to Chihiro no Kamikakushi
23273                               Shigatsu wa Kimi no Uso
24701                         Mushishi Zoku Shou 2nd Season
12355                          Ookami Kodomo no Ame to Yuki
1575                        Code Geass: Hangyaku no Lelouch
263                                          Hajime no Ippo
44        Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...
1                                              Cowboy Bebop
30276                                         One Punch Man
164                                           Mononoke Hime
7311                          Suzumiya Haruhi no Shoushitsu
17074                      Monogatari Series: Second Season
21939                                    Mushishi Zoku Shou
457                                                Mushishi
2001                             Tengen Toppa Gurren Lagann
...                                                     ...
33036     Suki ni Naru Sono Shunkan wo.: Kokuhaku Jikkou...
33013                                      Super Lovers OVA
27783                                        Sword Gai (TV)
34086                        Tales of Zestiria the X (2017)
34310     Tamagotchi Movie: Tanpen Himitsu no Otodoke Da...
33308     Tantei Opera Milky Holmes: Fun Fun Party Night...
34177                                         Tenshi no 3P!
34449                                        THE REFLECTION
32596                                  The Snack World (TV)
34416                   The Snack World: Hitogirai no Renny
33473                                 Tokyo Futago Athletic
21305                                        Trick or Alice
23275                                            Tsubu★Doll
34474                                Tsukipro The Animation
34498     Uchiage Hanabi, Shita kara Miru ka? Yoko kara ...
34076                                     Uchouten Kazoku 2
33064          Uchuu Senkan Yamato 2202: Ai no Senshi-tachi
33478                                            UQ Holder!
32924                                       Urara Meirochou
32012                                     Utakata Overdrive
34522                             Wake Up, Girls! Shin Shou
34022                                        Whistle! (ONA)
34467                                Yami Shibai 4th Season
32615                                           Youjo Senki
32222     Youkai Watch Movie 3: Soratobu Kujira to Doubl...
34471                                  Youkai Watch Movie 4
34284     Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou
34445          Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou
33035                                     Yuyushiki Special
33390                                         Zunda Horizon

                                                      genre     type episodes  \
anime_id
32281                  Drama, Romance, School, Supernatural    Movie        1
5114      Action, Adventure, Drama, Fantasy, Magic, Mili...       TV       64
28977     Action, Comedy, Historical, Parody, Samurai, S...       TV       51
9253                                       Sci-Fi, Thriller       TV       24
9969      Action, Comedy, Historical, Parody, Samurai, S...       TV       51
32935                Comedy, Drama, School, Shounen, Sports       TV       10
11061               Action, Adventure, Shounen, Super Power       TV      148
820                          Drama, Military, Sci-Fi, Space      OVA      110
15335     Action, Comedy, Historical, Parody, Samurai, S...    Movie        1
15417     Action, Comedy, Historical, Parody, Samurai, S...       TV       13
4181      Drama, Fantasy, Romance, Slice of Life, Supern...       TV       24
28851                                Drama, School, Shounen    Movie        1
918       Action, Comedy, Historical, Parody, Samurai, S...       TV      201
2904      Action, Drama, Mecha, Military, Sci-Fi, Super ...       TV       25
28891                Comedy, Drama, School, Shounen, Sports       TV       25
199                          Adventure, Drama, Supernatural    Movie        1
23273                Drama, Music, Romance, School, Shounen       TV       22
24701     Adventure, Fantasy, Historical, Mystery, Seine...       TV       10
12355                                Fantasy, Slice of Life    Movie        1
1575      Action, Mecha, Military, School, Sci-Fi, Super...       TV       25
263                          Comedy, Drama, Shounen, Sports       TV       75
44        Action, Drama, Historical, Martial Arts, Roman...      OVA        4
1           Action, Adventure, Comedy, Drama, Sci-Fi, Space       TV       26
30276     Action, Comedy, Parody, Sci-Fi, Seinen, Super ...       TV       12
164                              Action, Adventure, Fantasy    Movie        1
7311      Comedy, Mystery, Romance, School, Sci-Fi, Supe...    Movie        1
17074       Comedy, Mystery, Romance, Supernatural, Vampire       TV       26
21939     Adventure, Fantasy, Historical, Mystery, Seine...       TV       10
457       Adventure, Fantasy, Historical, Mystery, Seine...       TV       26
2001               Action, Adventure, Comedy, Mecha, Sci-Fi       TV       27
...                                                     ...      ...      ...
33036                        Comedy, Drama, Romance, School    Movie        1
33013                    Comedy, Drama, Romance, Shounen Ai      OVA        1
27783                                                Seinen       TV  Unknown
34086                            Action, Adventure, Fantasy       TV       12
34310                                                   NaN    Movie        1
33308                          Comedy, Mystery, Super Power  Special        1
34177                          Music, School, Slice of Life       TV  Unknown
34449                                   Action, Super Power       TV  Unknown
32596                      Adventure, Comedy, Fantasy, Kids       TV  Unknown
34416                      Adventure, Comedy, Fantasy, Kids    Movie        1
33473                                        Comedy, Sports      ONA        8
21305                                               Fantasy      OVA  Unknown
23275                                                 Music      OVA        5
34474                                                   NaN       TV  Unknown
34498                                                 Drama    Movie        1
34076                 Comedy, Drama, Fantasy, Slice of Life       TV  Unknown
33064                Action, Drama, Military, Sci-Fi, Space      OVA  Unknown
33478               Action, Fantasy, Magic, Sci-Fi, Shounen      NaN  Unknown
32924                         Comedy, Seinen, Slice of Life       TV  Unknown
32012                                        Fantasy, Music      OVA        1
34522                                          Drama, Music       TV  Unknown
34022                               School, Shounen, Sports      ONA  Unknown
34467                        Dementia, Horror, Supernatural       TV  Unknown
32615                                       Magic, Military       TV  Unknown
32222                            Comedy, Kids, Supernatural    Movie        1
34471                            Comedy, Kids, Supernatural    Movie        1
34284                  Drama, Fantasy, Magic, Slice of Life       TV        6
34445                  Drama, Fantasy, Magic, Slice of Life       TV        6
33035                                                   NaN  Special        1
33390                                                   NaN    Movie        1

          rating  members
anime_id
32281       9.37   200630
5114        9.26   793665
28977       9.25   114262
9253        9.17   673572
9969        9.16   151266
32935       9.15    93351
11061       9.13   425855
820         9.11    80679
15335       9.10    72534
15417       9.11    81109
4181        9.06   456749
28851       9.05   102733
918         9.04   336376
2904        8.98   572888
28891       8.93   179342
199         8.93   466254
23273       8.92   416397
24701       8.88    75894
12355       8.84   226193
1575        8.83   715151
263         8.83   157670
44          8.83   129307
1           8.82   486824
30276       8.82   552458
164         8.81   339556
7311        8.81   240297
17074       8.80   205959
21939       8.80   101351
457         8.78   300030
2001        8.78   562962
...          ...      ...
33036        NaN    10668
33013        NaN     5210
27783        NaN     6474
34086        NaN    10848
34310        NaN       51
33308        NaN      610
34177        NaN      359
34449        NaN      242
32596        NaN      107
34416        NaN       36
33473        NaN       75
21305        NaN     4481
23275        NaN     1060
34474        NaN      843
34498        NaN      531
34076        NaN     5934
33064        NaN     2058
33478        NaN     2341
32924        NaN     4305
32012        NaN      649
34522        NaN      381
34022        NaN      381
34467        NaN     1838
32615        NaN     6652
32222        NaN      237
34471        NaN      169
34284        NaN     2593
34445        NaN     4439
33035        NaN     2294
33390        NaN      160

[10486 rows x 6 columns]>

In [4]:
# インデックスにする列を列名で指定する
df = pd.read_csv(anime_csv, index_col='anime_id')
df.head()

,name,genre,type,episodes,rating,members
anime_id,,,,,,
32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [6]:
# Excelファイルを読み込む
anime_xlsx = os.path.join(base_url, 'anime.xlsx')

df = pd.read_excel(anime_xlsx)
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534
2,28851,Koe no Katachi,"Drama, School, Shounen",Movie,1,9.05,102733
3,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
4,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193

In [7]:
# 読み込むシートを指定する
df = pd.read_excel(anime_xlsx, sheetname='Movie')
df.head()

/Users/kawahara/.pyenv/versions/anaconda3-5.2.0/lib/python3.5/site-packages/pandas/io/excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534
2,28851,Koe no Katachi,"Drama, School, Shounen",Movie,1,9.05,102733
3,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
4,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193

In [8]:
# SQLを使用して読み込む
import os
from urllib.request import urlopen
import sqlite3

anime_db = os.path.join(base_url, 'anime.db')
res = urlopen(anime_db)
with open('anime.db', 'wb') as f:
    f.write(res.read())
    with sqlite3.connect(f.name) as conn:
        df = pd.read_sql('SELECT * FROM anime', conn)

df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [9]:
# HTMLファイルを読み込む
url = 'https://docs.python.org/3/py-modindex.html'

tables = pd.read_html(url, index_col=1)
tables[0].loc[:, 1:].dropna().head(10)

                                                               2
1
__future__                          Future statement definitions
__main__       The environment where the top-level script is ...
_dummy_thread        Drop-in replacement for the _thread module.
_thread                                 Low-level threading API.
abc                 Abstract base classes according to PEP 3119.
aifc           Read and write audio files in AIFF or AIFC for...
argparse       Command-line option and argument parsing library.
array          Space efficient arrays of uniformly typed nume...
ast               Abstract Syntax Tree classes and manipulation.
asynchat       Support for asynchronous command/response prot...